name: Instagram Bot

on:
  workflow_dispatch:
  schedule:
    # Example: 05:00, 13:00, and 21:00 UTC daily
    - cron: "0 5,13,21 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        # Removed 'schedule' package, added 'pillow' for instagrapi
        run: pip install instagrapi pillow
      - name: Create config file
        # Decode Base64 secret into config.json
        run: echo "${{ secrets.CONFIG_B64 }}" | base64 --decode > config.json
      - name: Verify config
        run: cat config.json
      - name: Run bot
        run: python insta_bot.py
