name: Instagram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "30 8,14,20,2 * * *"  # Runs at randomized times (±30 min)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install instagrapi schedule
      - name: Create config file
        run: echo "${{ secrets.CONFIG_JSON }}" > config.json
      - name: Run bot
        run: python insta_bot.py
