name: Instagram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "30 8,14,20,2 * * *"  # Runs at randomized times (±30 min)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install instagrapi schedule pillow
      - name: Create config file
        # Decode the Base64 secret into config.json
        run: echo "${{ secrets.CONFIG_B64 }}" | base64 --decode > config.json
      - name: Verify config file
        run: cat config.json  # Debugging step to ensure config.json is created
      - name: Run bot
        run: python insta_bot.py
